import { Event } from '@/types/event';
import { Ticket } from '@/types/ticket';
import { Venue } from '@/types/venue';
import { Vendor } from '@/types/vendor';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Summer Vibes Music Festival',
    description: 'The biggest outdoor music festival of the summer featuring top artists across three stages. Food trucks, art installations, and good vibes all day.',
    category: 'Music',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    startDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000).toISOString(),
    venueId: 'v1',
    venueName: 'Riverside Amphitheater',
    address: '123 Riverside Dr',
    city: 'Atlanta',
    state: 'GA',
    priceMin: 45,
    priceMax: 150,
    isFree: false,
    hasVip: true,
  },
  {
    id: '2',
    title: 'Jazz in the Park',
    description: 'A free community jazz evening in Piedmont Park. Bring your blanket and enjoy smooth sounds at sunset.',
    category: 'Music',
    imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
    startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    venueId: 'v2',
    venueName: 'Piedmont Park',
    city: 'Atlanta',
    state: 'GA',
    isFree: true,
    hasVip: false,
  },
  {
    id: '3',
    title: 'Neon Nights Rooftop Party',
    description: 'Atlanta\'s most exclusive rooftop nightlife experience. DJ sets, bottle service, and skyline views.',
    category: 'Nightlife',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
    startDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    venueId: 'v3',
    venueName: 'Sky Lounge ATL',
    address: '500 Peachtree St NE',
    city: 'Atlanta',
    state: 'GA',
    priceMin: 30,
    priceMax: 200,
    isFree: false,
    hasVip: true,
  },
  {
    id: '4',
    title: 'Kids Art & Craft Festival',
    description: 'A fun-filled day of art, crafts, face painting, and interactive activities for kids of all ages.',
    category: 'Kid Friendly',
    imageUrl: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=800',
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    venueId: 'v4',
    venueName: 'Centennial Park',
    city: 'Atlanta',
    state: 'GA',
    priceMin: 10,
    isFree: false,
    hasVip: false,
  },
  {
    id: '5',
    title: 'Food Truck Mania',
    description: 'Over 40 food trucks, live cooking demos, and craft beer garden. Atlanta\'s favorite food festival returns.',
    category: 'Food & Drink',
    imageUrl: 'https://images.unsplash.com/photo-1567129938501-6a4e3c0e5b3e?w=800',
    startDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    venueId: 'v5',
    venueName: 'Old Fourth Ward Park',
    city: 'Atlanta',
    state: 'GA',
    priceMin: 5,
    priceMax: 15,
    isFree: false,
    hasVip: false,
  },
  {
    id: '6',
    title: 'ATL Arts & Culture Night',
    description: 'A curated evening celebrating Atlanta\'s vibrant arts scene with live performances, gallery exhibitions, and artist meet-and-greets.',
    category: 'Arts & Culture',
    imageUrl: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800',
    startDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    venueId: 'v6',
    venueName: 'High Museum of Art',
    city: 'Atlanta',
    state: 'GA',
    priceMin: 25,
    priceMax: 75,
    isFree: false,
    hasVip: true,
  },
];

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 't1',
    eventId: '3',
    eventTitle: 'Neon Nights Rooftop Party',
    eventDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    ticketType: 'General Admission',
    quantity: 2,
    qrCodeValue: 'TICKET-T1-NEON-2024',
    status: 'active',
    isVip: false,
  },
  {
    id: 't2',
    eventId: '1',
    eventTitle: 'Summer Vibes Music Festival',
    eventDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    ticketType: 'VIP Table',
    quantity: 1,
    qrCodeValue: 'TICKET-T2-SUMMER-VIP',
    status: 'active',
    isVip: true,
  },
];

export const MOCK_VENUES: Venue[] = [
  {
    id: 'v1',
    name: 'Riverside Amphitheater',
    description: 'Atlanta\'s premier outdoor concert venue with stunning river views and capacity for 10,000 guests.',
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    address: '123 Riverside Dr',
    city: 'Atlanta',
    state: 'GA',
    categories: ['Music', 'Festival'],
  },
  {
    id: 'v3',
    name: 'Sky Lounge ATL',
    description: 'Exclusive rooftop venue with panoramic Atlanta skyline views. Perfect for nightlife events and private parties.',
    imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800',
    address: '500 Peachtree St NE',
    city: 'Atlanta',
    state: 'GA',
    categories: ['Nightlife'],
  },
];

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'vnd1',
    name: 'Elite Catering Co.',
    description: 'Premium catering for events of all sizes. Farm-to-table menus and impeccable service.',
    category: 'Catering',
    city: 'Atlanta',
    state: 'GA',
  },
  {
    id: 'vnd2',
    name: 'Pulse Photography',
    description: 'Award-winning event photography capturing every moment with style.',
    category: 'Photography',
    city: 'Atlanta',
    state: 'GA',
  },
];
